#!/usr/bin/env ansible-playbook
- name: Gather tor version and spit out results
  hosts: securedrop
  gather_facts: "yes"
  tasks:
    - name: extract tor version
      shell: |
        apt-cache policy tor | sed -e 's/^\s*Installed:\ \(\S*\)/\1/g;tx;d;:x'
      changed_when: false
      register: extract_tor_version

    - name: Form tor_versions dictionary
      set_fact:
        tor_versions: "{{ tor_versions|default([]) + [{
            'value': hostvars[item]['extract_tor_version']['stdout'],
            'title': hostvars[item]['ansible_hostname'],
            'short': True }] }}"
      delegate_to: localhost
      with_items: "{{ groups['securedrop'] }}"

    - name: Blast slack info
      slack:
        token: "{{ lookup('env', 'CI_SLACK_TOKEN') }}"
        channel: "{{ lookup('env', 'CI_SLACK_CHANNEL') }}"
        icon_url: "https://check.torproject.org/torcheck/img/tor-on.png"
        username: "Jenkins"
        attachments:
          - title: CI {{'PASSED' if ci_pass else 'FAILED'}} for Tor nightly
            color: "{{ 'good' if ci_pass else 'danger' }}"
            text: "Build URL {{ lookup('env', 'BUILD_URL') }}"
            fields: "{{ tor_versions }}"
      run_once: true
      delegate_to: localhost
  vars:
    ci_pass: "{{ lookup('env', 'CI_BUILD_RESULT')|bool }}"
